### ISSUE TITLE
FMU-Builder: java.lang.ClassNotFoundException: no.ntnu.ais.fmu4j.export.fmi2.Fmi2Slave when generating FMU

### ISSUE THREAD

**Issue by hannesN** [Vico-platform/FMU4j#6]
I try to create an FMU after building a fat jar with maven. Sadly, I get a ClassNotFoundException.

Oddly, the build creates a fmu-builder-app just containing a Manifest file. Is this correct?

Thanks
Hannes

**Comment by markaren** [comment]
On phone, but I think you are looking for fmu-builder directory, not the one with app in it.

**Comment by markaren** [comment]
Disregard previous comment. Like the README states, call `./gradlew installDist` and the executable (not JAR) is located in `fmu-builder-app/build/install`
